backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads" # Thư mục lưu trữ hình ảnh trên repo
public_folder: "/images/uploads" # Thư mục hình ảnh công khai

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Home Page"
        file: "index.html"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "text" }
      
